version: "3"
services:
  proxy:
    image: gcr.io/api-circleci-test/proxy:latest
    volumes:
         - './db.json:/app/database/db.json'
    ports:
      - "80:80"
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - proxy
    